version: 0.2

env:
  variables:
    HUGO_VERSION: "0.124.1"

phases:
  install:
    commands:
      - echo "Installing Hugo $HUGO_VERSION..."
      - curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz -o hugo.tar.gz
      - tar -xzf hugo.tar.gz
      - mv hugo /usr/local/bin/
  build:
    commands:
      - cd blog
      - hugo --minify
  post_build:
    commands:
      - echo "Deploying to $WEBSITE_BUCKET"
      - aws s3 sync public/ s3://$WEBSITE_BUCKET --delete
