AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
Outputs:
  WebsiteBucketName:
    Description: "S3 bucket for Hugo site"
    Value: !Ref WebsiteBucket
    Export:
      Name: WebsiteBucketName
