AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Polly TTS for blog posts

Globals:
  Function:
    Timeout: 120
    Runtime: python3.12
    MemorySize: 256

Parameters:
  WebsiteBucketName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /sensei/blog/bucket-name
  PostChangedTopicArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /sensei/blog/post-changed-topic-arn

Resources:

  PollyDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: sensei-polly-dlq
      MessageRetentionPeriod: 1209600
      Tags:
        - Key: Project
          Value: aws-sensei
        - Key: Service
          Value: blog
        - Key: Component
          Value: api-polly

  PollyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sensei-polly
      Handler: handler.lambda_handler
      CodeUri: src/
      Environment:
        Variables:
          WEBSITE_BUCKET: !Ref WebsiteBucketName
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt PollyDLQ.Arn
      Events:
        PostChanged:
          Type: SNS
          Properties:
            Topic: !Ref PostChangedTopicArn
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: polly:SynthesizeSpeech
              Resource: "*"
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: !Sub "arn:aws:s3:::${WebsiteBucketName}/*"

Outputs:
  DLQUrl:
    Description: Polly Dead Letter Queue URL
    Value: !Ref PollyDLQ
  DLQArn:
    Description: Polly Dead Letter Queue ARN
    Value: !GetAtt PollyDLQ.Arn

